// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(TankDbContext))]
    partial class TankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("AmmunitionType", b =>
                {
                    b.Property<int>("AmmunitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmmunitionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmmunitionTypeName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Caliber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ExplosiveMassTNT")
                        .HasColumnType("TEXT");

                    b.Property<int>("GunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MuzzleVelocity")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProjectileMass")
                        .HasColumnType("TEXT");

                    b.HasKey("AmmunitionId");

                    b.ToTable("AmmunitionTypes", (string)null);
                });

            modelBuilder.Entity("ArmorPenetration", b =>
                {
                    b.Property<int>("PenetrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmmunitionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("m1000_0s")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("m1000_30s")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("m1000_60s")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("m100_0S")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("m100_30s")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("m100_60s")
                        .HasColumnType("TEXT");

                    b.HasKey("PenetrationId");

                    b.HasIndex("AmmunitionId")
                        .IsUnique();

                    b.ToTable("ArmorPenetrations", (string)null);
                });

            modelBuilder.Entity("ArmorSpecification", b =>
                {
                    b.Property<int>("ArmorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HullFront")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HullRear")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HullSide")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecificationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TurretFront")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TurretRear")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TurretSide")
                        .HasColumnType("TEXT");

                    b.HasKey("ArmorId");

                    b.HasIndex("SpecificationId")
                        .IsUnique();

                    b.ToTable("ArmorSpecifications", (string)null);
                });

            modelBuilder.Entity("GunAmmunition", b =>
                {
                    b.Property<int>("GunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmmunitionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GunId", "AmmunitionId");

                    b.HasIndex("AmmunitionId");

                    b.ToTable("GunAmmunition");
                });

            modelBuilder.Entity("GunSpecification", b =>
                {
                    b.Property<int>("GunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmmunitionCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Caliber")
                        .HasColumnType("TEXT");

                    b.Property<string>("GunName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReloadTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecificationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TurretRotationSpeed")
                        .HasColumnType("TEXT");

                    b.HasKey("GunId");

                    b.ToTable("GunSpecifications", (string)null);
                });

            modelBuilder.Entity("Informations", b =>
                {
                    b.Property<int>("InformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("funfact")
                        .HasColumnType("TEXT");

                    b.HasKey("InformationId");

                    b.ToTable("Informations", (string)null);
                });

            modelBuilder.Entity("Tank", b =>
                {
                    b.Property<int>("TankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("JpgPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model3DPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("TankType")
                        .HasColumnType("TEXT");

                    b.HasKey("TankId");

                    b.ToTable("Tanks", (string)null);
                });

            modelBuilder.Entity("TankSpecification", b =>
                {
                    b.Property<int>("SpecificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrewCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EnginePower")
                        .HasColumnType("TEXT");

                    b.Property<int>("GunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxBackwardSpeed")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxForwardSpeed")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PowerToWeightRatio")
                        .HasColumnType("TEXT");

                    b.Property<int>("TankId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("SpecificationId");

                    b.HasIndex("GunId");

                    b.HasIndex("TankId")
                        .IsUnique();

                    b.ToTable("TankSpecifications", (string)null);
                });

            modelBuilder.Entity("VerticalGuidance", b =>
                {
                    b.Property<int>("VGId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Min")
                        .HasColumnType("TEXT");

                    b.HasKey("VGId");

                    b.HasIndex("GunId")
                        .IsUnique();

                    b.ToTable("VerticalGuidances", (string)null);
                });

            modelBuilder.Entity("ArmorPenetration", b =>
                {
                    b.HasOne("AmmunitionType", "Ammunition")
                        .WithOne("ArmorPenetration")
                        .HasForeignKey("ArmorPenetration", "AmmunitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ammunition");
                });

            modelBuilder.Entity("ArmorSpecification", b =>
                {
                    b.HasOne("TankSpecification", "Specifications")
                        .WithOne("Armor")
                        .HasForeignKey("ArmorSpecification", "SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("GunAmmunition", b =>
                {
                    b.HasOne("AmmunitionType", "Ammunition")
                        .WithMany("GunAmmunitions")
                        .HasForeignKey("AmmunitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GunSpecification", "Gun")
                        .WithMany("GunAmmunitions")
                        .HasForeignKey("GunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ammunition");

                    b.Navigation("Gun");
                });

            modelBuilder.Entity("TankSpecification", b =>
                {
                    b.HasOne("GunSpecification", "Gun")
                        .WithMany("Specifications")
                        .HasForeignKey("GunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tank", "Tank")
                        .WithOne("Specifications")
                        .HasForeignKey("TankSpecification", "TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gun");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("VerticalGuidance", b =>
                {
                    b.HasOne("GunSpecification", "Gun")
                        .WithOne("VerticalGuidance")
                        .HasForeignKey("VerticalGuidance", "GunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gun");
                });

            modelBuilder.Entity("AmmunitionType", b =>
                {
                    b.Navigation("ArmorPenetration");

                    b.Navigation("GunAmmunitions");
                });

            modelBuilder.Entity("GunSpecification", b =>
                {
                    b.Navigation("GunAmmunitions");

                    b.Navigation("Specifications");

                    b.Navigation("VerticalGuidance");
                });

            modelBuilder.Entity("Tank", b =>
                {
                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("TankSpecification", b =>
                {
                    b.Navigation("Armor");
                });
#pragma warning restore 612, 618
        }
    }
}
